# Мандаин тут нихуя не трогай если не гей
# Мандаин тут нихуя не трогай если не Юра
# Мандаин тут нихуя не трогай если не Андрей
#
#Если корды триста ты сосёшь у трактариста
#каардината пре которай южнее нильзя ставеть деспенсер
coords: 200
#
#
#
#
#
#
#
#
#
#
message:
  blocked: "&c&l&nНе, не, не, крашить сервер блять нельзя!!!"